<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxcartpro
 * @version    2.4.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
?>
<script type="text/javascript">
	function addCartItem()
	{
		var qty = parseNumber($$('.amount ')[0].down('a').innerHTML);
		$$('.amount ')[0].down('a').innerHTML = ++qty;
	}
</script>
<div class="ajaxcartpro_confirm" style="display: none;">
	<p><span id="acp_product_name"><?php echo $this->__('Item(s)') ?></span><?php echo $this->__(' added to cart') ?></p>
	
	<div onclick="addCartItem();">
		<a href="#" id="aw_acp_continue" class="focus" onclick="$$('.ajaxcartpro_confirm')[0].style.display='none';return false;">Ver mais produtos?<?php echo Mage::helper('ajaxcartpro')->displayCountdown() ?></a>
	</div>

	<?php echo $this->__('ou')?>
	<a href="<?php echo Mage::getUrl('checkout/cart')?>" id="aw_acp_checkout">
		Finalizar compra
	</a>
</div>

